# Generated by Django 5.2.13 on 2026-04-28 23:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_conversation_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversation",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
